[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "python-interop"
version = "0.1.0"
description = "Python bindings for MyStruct"
requires-python = ">=3.7"

[tool.maturin]
module-name = "python_interop"
python-source = "python"
features = []
